### ISSUE TITLE
Deprecate in favor of hhvm/user-documentation?

### ISSUE THREAD

**Issue by fredemmott** [facebookarchive/hack-example-site#20]
A real site is better than an example, and we're actively maintaining that one :)

**Comment by jwatzman** [comment]
+1. The actual examples in here are useful, particularly the get/put one -- is that useful to port into the new docs, or have the docs pages point at their source code if user-documentation already does something like that?

**Comment by fredemmott** [comment]
IMO the documentation should:

 - copy the examples
 - also suggest https://git.simon.geek.nz/91-carriage/hack-requests and https://github.com/fredemmott/psr7-http-message-hhi (the docs site uses this, implementation comes from https://github.com/zendframework/zend-diactoros/)

**Comment by JoelMarcey** [comment]
I am going to kill the cookbook as I move hacklang.org to gh-pages.

**Comment by JoelMarcey** [comment]
The new hacklang.org is out. Cookbook gone. I will archive this site when I get the chance.

**Comment by JoelMarcey** [comment]
The repo has been archived.
